version: '3'
services:
  etcd:
    build:
      context: .
      dockerfile: ./docker/etcd/Dockerfile
    image: nokamoto/etcd:latest
  poc-go-etcd:
    build:
      context: .
      dockerfile: ./docker/poc-go-etcd/Dockerfile
    image: nokamoto/poc-go-etcd:latest
